import React from 'react'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainMenu from '@/components/MainMenu/MainMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>el head</head>
      <body className={inter.className}>
        <header>

          <MainMenu />
        </header>
        {children}
      </body>
    </html>
  )
}
